version: '3'
services:
  frontend:
    build: ./vending-ui
    ports:
      - "3000:3000"
  backend:
    build: ./vending
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/vending
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: vending
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - "3306:3306"
    #volumes:
    #  - ./mysql-data:/var/lib/mysql