jwt:
  secret: mysupersecretmysupersecretmysupersecretmysupersecretmysupersecretmysupersecretmysupersecretmysupersecretmysupersecretmysupersecretmysupersecretmysupersecretmysupersecretmysupersecretmysupersecretmysupersecretmysupersecretmysupersecret

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/vending?serverTimezone=UTC
    username: myuser
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    root: INFO
server:
  tomcat:
    uri-encoding: UTF-8

